services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

#  backend:
#    build: ./backend
#    depends_on:
#      - db
#    environment:
#      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb
#    ports:
#      - "8000:8000"
#    networks:
#      - app-network

  api:
    build: ./app
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
#      NEXT_PUBLIC_API_URL: http://localhost:8000  # o el host del backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    volumes:
      - .:/app

volumes:
  postgres_data:

networks:
  app-network:
