services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      JWT_KEY: "5ySbfCyvw6797YRB7pAlMPnkHSdqrNqwnF3Z_s1t2jA"
    volumes:
      - .:/app

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
